"use client";
import { useCallback, useEffect, useState } from "react";
import { Card } from "@/components/ui/Card";
import { Badge } from "@/components/ui/Badge";
import { api } from "@/lib/resources";

type Summary = { connector_id: string; connector_name: string; connector_type?: string; status: string; received: number; accepted: number; rejected: number; duplicates: number; latest_observed_at: string | null; latest_received_at: string | null; freshness_status: string };
export default function IngestionPage() {
 const [items,setItems]=useState<Summary[]>([]); const [error,setError]=useState<string|null>(null);
 const load=useCallback(async()=>{try{setItems(await api<Summary[]>("/telemetry/summary"));setError(null)}catch(e){setError((e as Error).message)}},[]);
 useEffect(()=>{void load();const id=window.setInterval(()=>void load(),15000);return()=>window.clearInterval(id)},[load]);
 return <div className="animate-fade-in-up"><header className="mb-6"><h1>Data operations</h1><p className="mt-1 text-sm text-muted-foreground">Telemetry arrival, quality, and connector health for this organisation.</p></header>{error&&<p className="mb-4 text-sm text-red">Unable to load ingestion health: {error}</p>}<div className="grid gap-4 md:grid-cols-3"><Card><p className="text-xs text-muted-foreground">Active connectors</p><p className="mt-1 text-3xl font-extrabold">{items.length}</p></Card><Card><p className="text-xs text-muted-foreground">Accepted readings</p><p className="mt-1 text-3xl font-extrabold">{items.reduce((a,b)=>a+b.accepted,0).toLocaleString()}</p></Card><Card><p className="text-xs text-muted-foreground">Quality rejects</p><p className="mt-1 text-3xl font-extrabold">{items.reduce((a,b)=>a+b.rejected,0).toLocaleString()}</p></Card></div><Card className="mt-4" padded={false}><div className="overflow-x-auto p-5"><table className="w-full"><thead><tr>{["Connector","Status","Freshness","Accepted","Rejected","Duplicates","Last observed"].map(h=><th key={h} className="border-b border-border px-2 py-2 text-left text-xs text-muted-foreground">{h}</th>)}</tr></thead><tbody>{items.map(item=><tr key={item.connector_id}><td className="border-b border-border px-2 py-3 font-semibold">{item.connector_name}</td><td className="border-b border-border px-2 py-3"><Badge tone={item.status==="healthy"?"healthy":"critical"}>{item.status}</Badge></td><td className="border-b border-border px-2 py-3"><Badge tone={item.freshness_status==="fresh"?"healthy":item.freshness_status==="stale"?"watch":"critical"}>{item.freshness_status}</Badge></td><td className="border-b border-border px-2 py-3">{item.accepted}</td><td className="border-b border-border px-2 py-3">{item.rejected}</td><td className="border-b border-border px-2 py-3">{item.duplicates}</td><td className="border-b border-border px-2 py-3 text-sm">{item.latest_observed_at?new Date(item.latest_observed_at).toLocaleString():"No accepted data"}</td></tr>)}</tbody></table>{items.length===0&&<p className="py-10 text-center text-sm text-muted-foreground">No connectors configured.</p>}</div></Card></div>;
}
